### ISSUE TITLE
Buttons in ButtonGroup don't correctly connect

### ISSUE THREAD

**Issue by microdou** [TheComputerM/svelte-materialify#141]
### Issue:
Buttons in ButtonGroup don't correctly connect.

### Screenshot:
![image](https://user-images.githubusercontent.com/8561307/108738606-cb3b2480-7501-11eb-86f9-d3e8b4a4a96f.png)

### How to Reproduce:
https://github.com/microdou/svelte-test/tree/svelte-materialify-buttongroup
``` sh
git clone -b svelte-materialify-buttongroup https://github.com/microdou/svelte-test
cd svelte-test
npm i
npm run dev

# Then open up browser at http://localhost:5000
```
### Browsers:
The issue exists on both Firefox & Chrome.

**Comment by betaboon** [comment]
my initial research:
this seems to be due to both `.s-btn` and `.s-btn-group-item` applying to the elements and sometimes `.s-btn` takes precedence (most likely due to ordering in the final css-file).

workaround:
```scss
:global(.s-btn-group-item) {
  border-radius: 0 !important;
}
:global(.s-btn-group-item:first-child) {
  border-top-left-radius: inherit !important;
  border-bottom-left-radius: inherit !important;
}
:global(.s-btn-group-item:last-child) {
  border-top-right-radius: inherit !important;
  border-bottom-right-radius: inherit !important;
}
```
