### ISSUE TITLE
The app-bar component should transitioning necessary property

### ISSUE THREAD

**Issue by donnisnoni** [TheComputerM/svelte-materialify#197]
I've got some weird transition when using button component inside app-bar component when switch theme.

https://user-images.githubusercontent.com/16399020/112485033-7404ca00-8db5-11eb-8220-8cc35fc416f5.mp4

BTW it's solved with this
```css
.s-app-bar {
	transition-property: color;
}
```
