### ISSUE TITLE
Color for Textarea

### ISSUE THREAD

**Issue by erbaafidotama** [TheComputerM/svelte-materialify#97]
Hallo..
I try to change color for Textarea, but Textarea color still using class primary-text. I have put other class for change color, like in my code. How to solve my problem?
![code](https://user-images.githubusercontent.com/22489268/103770555-c953f980-5058-11eb-89ef-f81320fba326.png)

Thx

**Comment by DinCahill** [comment]
I got something working, but I don't know how to do it properly. I had to edit `TextField.scss` in the source. 

https://user-images.githubusercontent.com/510163/103832189-9b30e280-5075-11eb-859c-7e034a83cd72.mp4

`TextField.scss`
```css
.colorTextFocused .s-text-field__wrapper {
  input,
  label {
    &:focus,
    &:active {
      color: currentColor;
    }
  }
}

.colorTextAlways .s-text-field__wrapper {
  &::before {
    border-color: currentColor;
    color: currentColor;
  }
  input,
  label {
    color: currentColor;
  }
}
```
`index.svelte`
```js
<Row>
  <Col>
    <TextField outlined color="orange" class="colorTextAlways" placeholder="Orange">Orange</TextField>
    <TextField outlined color="green" class="colorTextAlways" placeholder="Green">Green</TextField>
    <TextField outlined color="red" class="colorTextAlways" placeholder="Red">Red</TextField>
  </Col>
  <Col>
    <TextField outlined color="orange" class="colorTextFocused" placeholder="Orange">Orange</TextField>
    <TextField outlined color="green" class="colorTextFocused" placeholder="Green">Green</TextField>
    <TextField outlined color="red" class="colorTextFocused" placeholder="Red">Red</TextField>
  </Col>
</Row>
```
